name: CI/CD Pipeline 

 

on: 

  push: 

    branches: 

      - main          # Trigger the workflow when code is pushed to 'main' 

  pull_request: 

    branches: 

      - main          # Trigger the workflow on pull requests to 'main' 

 

jobs: 

  build: 

    runs-on: ubuntu-latest 

    strategy:

      matrix: 

        environment: [staging, production]  # Define multiple environments 

    steps: 

    - name: Checkout Code 

      uses: actions/checkout@v2       # Check out the repository code 

 

    - name: Set up Node.js 

      uses: actions/setup-node@v2 

      with: 

        node-version: '14'            # Set up Node.js version 14 

 

    - name: Install Dependencies 

      run: npm install                # Install Node.js dependencies 

 

    - name: Run Tests 

      run: npm test                   # Run tests  
jobs: 

  build-and-deploy: 

    runs-on: ubuntu-latest 

 

    steps: 

      - name: Checkout Repository 

        uses: actions/checkout@v2 

 

      - name: Log in to Azure 

        uses: azure/login@v1 

        with: 

          creds: ${{ secrets.AZURE_CREDENTIALS2 }} 

 

      - name: Run Tests 

        run: npm test 

 

      - name: Display Deployment Start 

        run: echo "Starting deployment to Azure..."  # Output message to indicate the start of the deployment 

 

      - name: Deploy to Azure App Service 

        run: echo "Deploying code to Azure App Service..."  # Output message for progress tracking 

 

      - name: Deploy to Azure App Service 

        uses: azure/webapps-deploy@v2 

        with: 

          app-name: "my-first-app" 

          package: . 
